name: PetMonitoringFrontend-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Copy Code to Runner
      - name: Set timezone to Asia/Taipei
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"
          timezoneMacos: "Asia/Taipei"

      - name: Set up Node.js #Setup NodeJs Version
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install

      - name: try to build the project
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist